version: "3.1"

services:
  mqtttomysql:
    image: wagonorge/vaex-mqtt-mysql-store
    depends_on:
      - db

  simulation:
    image: wagonorge/vaex-water-simulator
    depends_on:
      - db

  leakdetection:
    image: wagonorge/va-leak-detection
    depends_on:
      - db
      - simulation

  grafana:
    image: jonev/grafana-with-plugins
    ports:
      - 3000:3000
    depends_on:
      - db
  
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always 
    ports:
      - 1883:1883
      - 9001:9001

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    security_opt:
      - seccomp:unconfined
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/Docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer_data:
